modLoader="kotlinforforge"
loaderVersion="[1.12,)"
license = "Apache-2.0"

[[mods]]
modId = "deserted"
version = "${version}"
displayName = "Deserted"
authors = "Skyternity Modding Group"
description = '''
A Minecraft Mod that aims to expand the rough, dry and dusty deserts!
'''
logoFile = "assets/deserted/icon.png"

[[dependencies.deserted]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deserted]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deserted]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

